import "@/styles/globals.css";

import { type Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import AuthProvider from "./_components/session-provider";
import Navbar from "@/components/Navbar";
import "@/styles/fonts.css";
import TopStrip from "@/components/TopStrip";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={` ${spaceGrotesk.variable}`}>
      <body className="bg-[#EDE9E5]">
        <AuthProvider>
        <TopStrip />

          <Navbar />
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
